# Generated by Django 6.0.7 on 2026-07-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_userprofile_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('player', 'Player'), ('coach', 'Coach'), ('head_coach', 'Head Coach')], max_length=15),
        ),
    ]
