# Generated by ChatGPT on 2026-07-08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve', 'Approve'), ('deny', 'Deny'), ('delete', 'Delete'), ('role_change', 'Role Change')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='actions', to='team.userprofile')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='target_logs', to='team.userprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
